/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveShipments: typeof import('./src/components/dashboard/ActiveShipments.vue')['default']
    AddingModal: typeof import('./src/components/AddingModal.vue')['default']
    BlockAssignModal: typeof import('./src/components/BlockAssignModal.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DateRangePicker: typeof import('./src/components/DateRangePicker.vue')['default']
    DateTimePicker: typeof import('./src/components/DateTimePicker.vue')['default']
    DefaultModal: typeof import('./src/components/DefaultModal.vue')['default']
    DeleteModal: typeof import('./src/components/DeleteModal.vue')['default']
    EditingModal: typeof import('./src/components/EditingModal.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    FilteringModal: typeof import('./src/components/FilteringModal.vue')['default']
    InventoryAgeChart: typeof import('./src/components/dashboard/InventoryAgeChart.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MapBlockAssignModal: typeof import('./src/components/MapBlockAssignModal.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NominatePasswordModal: typeof import('./src/components/NominatePasswordModal.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    RecentProductionRuns: typeof import('./src/components/dashboard/RecentProductionRuns.vue')['default']
    ResponseModal: typeof import('./src/components/ResponseModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SessionExpiredModal: typeof import('./src/components/SessionExpiredModal.vue')['default']
    SmartAssignModal: typeof import('./src/components/SmartAssignModal.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    TodayProduction: typeof import('./src/components/dashboard/TodayProduction.vue')['default']
    TotalBatchesToday: typeof import('./src/components/dashboard/TotalBatchesToday.vue')['default']
    TotalInventoryItems: typeof import('./src/components/dashboard/TotalInventoryItems.vue')['default']
    UnauthorizedPage: typeof import('./src/components/UnauthorizedPage.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
    WarehouseUtilization: typeof import('./src/components/dashboard/WarehouseUtilization.vue')['default']
  }
}
