/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddingModal: typeof import('./src/components/AddingModal.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DateRangePicker: typeof import('./src/components/DateRangePicker.vue')['default']
    DateTimePicker: typeof import('./src/components/DateTimePicker.vue')['default']
    DefaultModal: typeof import('./src/components/DefaultModal.vue')['default']
    DeleteModal: typeof import('./src/components/DeleteModal.vue')['default']
    EditingModal: typeof import('./src/components/EditingModal.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    FilteringModal: typeof import('./src/components/FilteringModal.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NominatePasswordModal: typeof import('./src/components/NominatePasswordModal.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    ResponseModal: typeof import('./src/components/ResponseModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
  }
}
